### ISSUE TITLE
How do you pass parameters to build.cake from build.ps1?

### ISSUE THREAD

**Issue by xclayl** [cake-build/resources#13]
My build.cake file has this:

`var version = Argument("build_version", "0.9.0-beta");`

I'm trying to pass the information to build.ps1:

`powershell .\build.ps1 -build_version=%VERSION%`

This doesn't seem to work. The documentation talks about cake.exe, but that's some internal exe that I don't use directly, right? (Why does the documentation even talk about cake.exe? http://cakebuild.net/docs/fundamentals/configuration)

Is there confusion internally what we should be using, cake.exe vs build.ps1?

**Comment by xclayl** [comment]
Found it:
http://cakebuild.net/docs/tutorials/extending-the-bootstrapper

My gut feeling is that build.ps1's purpose should just download and update cake.exe and we call cake.exe directly.  build.ps1 is getting in the way and making it more difficult to work with.  Why would I modify your code?  I would never update the build.ps1 script since I've now customized it.
I'm going to look to see how to use build.ps1 as just a downloader/updater.

**Comment by devlead** [comment]
Custom arguments with the default bootstrapper can be passed without need to change the `build.ps1` using the `-ScriptArgs` parameter, example:
Using this cake script
```cake
var version = Argument("build_version", "0.9.0-beta");
Information("build_version: {0}", version);
```
will output this as default
![image](https://cloud.githubusercontent.com/assets/1647294/19239489/916bd776-8f06-11e6-8413-ff8362dc3d58.png)

But if you specify your custom parameter like this:
```PowerShell
.\build.ps1 -ScriptArgs '--build_version="1.0"'
```
It'll output
![image](https://cloud.githubusercontent.com/assets/1647294/19239536/c724ef7e-8f06-11e6-94b9-7af8ccf87e58.png)

Cake arguments are separated by space so if you had two arguments it could look something like this:
```PowerShell
.\build.ps1 -ScriptArgs '--build_version="1.0" --nuget_version="1.0.1"'
```

**Comment by xclayl** [comment]
I figured it out eventually. I wasn't at a powershell prompt. I was at a command prompt.  I think I ran into another issue, so let me have a go at it to make sure it works completely... (powershell security)

**Comment by xclayl** [comment]
The command that worked in the end is:

`powershell -ExceutionPolicy Unrestricted -File build.ps1 -ScriptArgs '-build_version="1.0"'`

It's not easy working through how to convert this, http://cakebuild.net/docs/cli/usage, into the command above.  

I would like to write a cake.bootstrapper.exe program along the lines of paket.bootstrapper.exe (ie it downloads only) and then we (users of cake) can call cake.exe directly.

If not, then let's update the documentation to show examples from:

- Windows command line
- Powershell command line
- Bash command line

Documenation and new-user adoption will be easier with a cake.bootstrapper.exe approach.

**Comment by gep13** [comment]
@xclayl we would welcome any suggestions/PR's on how to improve the documentation in this area.  Would you be in a position to submit a PR?  Thanks!

**Comment by BenGrayAdams** [comment]
@devlead in case any googlers find this, the answer you gave above for passing multiple arguments through build.ps1 to cake would not work on my box...powershell differences in 2019?  This worked for me (had to lose the tics and add comma separation):
`.\build.ps1 -ScriptArgs -build_version="1.0",-nuget_version="1.0.1"'

**Comment by loning** [comment]
> @devlead in case any googlers find this, the answer you gave above for passing multiple arguments through build.ps1 to cake would not work on my box...powershell differences in 2019? This worked for me (had to lose the tics and add comma separation):
> 
> `.\build.ps1 -ScriptArgs -build_version="1.0",-nuget_version="1.0.1"`

./build.sh -target=Test-with-Codecov-N --parts=3 --n=1

works for me

**Comment by sakennedy** [comment]
Google sent me here so thought I would record my experience. I could not find any combination of inputs to pass a target (I'm running from a powershell prompt in Windows 10 Windows Terminal app).
I keep getting the same unhelpful error. I ended up temporarily modifying the 'build.cake' file to execute the 'target' I wanted. This seems all too hard for a novice user.

 .\build.ps1 -ScriptArgs -target="NugetRestore"
Preparing to run build script...
Running build script...
Multiple arguments with the same name (target).

Usage: Cake.exe [script] [--verbosity=value]
                [--showdescription] [--dryrun] [..]

Example: Cake.exe
Example: Cake.exe build.cake --verbosity=quiet
Example: Cake.exe build.cake --showdescription

Options:
    --verbosity=value    Specifies the amount of information to be displayed.
                         (Quiet, Minimal, Normal, Verbose, Diagnostic)
    --debug              Performs a debug.
    --showdescription    Shows description about tasks.
    --dryrun             Performs a dry run.
    --version            Displays version information.
    --help               Displays usage information.
    --mono               Uses the Mono Compiler, rather than Roslyn script engine.
    --experimental       Uses the nightly builds of Roslyn script engine.
