### ISSUE TITLE
How do you pass environment vars via build.ps1 to build.cake?

### ISSUE THREAD

**Issue by xclayl** [cake-build/resources#14]
This evironment var seems to be ignored:
```
SET BUILD_VERSION=0.9.1-beta
powershell .\build.ps1 
```

My build.cake file has the following:
```
var version = Argument("build_version", "0.9.0-beta");

Task("Default")
.Does(() => {
	Information("version=" + version);
});
```

**Comment by gep13** [comment]
Why do you need to pass environment variables into your build.cake file? Why not simply read those environment variables within the build.cake file?

**Comment by kitforbes** [comment]
As @gep13 mentioned, you can read environment variables with `var theValue = EnvironmentVariable("ENV_VAR");`. More information can be found [here](http://cakebuild.net/api/cake.common/7bef281e).

It looks like you want to allow the `Argument()` method to take more options like `Argument("scriptVariable", "ENVIRONMENT_VARIABLE", "Or default value");`. I initially wanted something like this so I could overwrite in different scenarios (custom config file, local execution, or build server) so wrote my own module for it. After I got that working, I realised I was just over complicating things so simplified my process.

**Comment by xclayl** [comment]
I assumed the args worked the same way as the cake configuration:
http://cakebuild.net/docs/fundamentals/configuration

I've been struggling to find a way to pass information from TeamCity to build.cake.   The environment variable works, so I might do that (set environment var in a batch file before calling build.ps1)

**Comment by gep13** [comment]
What information from TeamCity are you looking for?

**Comment by xclayl** [comment]
It's a version number -- this is used for packing the nuget files in build.cake.  The steps we have are basically:

1) TeamCity creates a version number
2) TeamCity executes some steps using the version number
3) TeamCity calls cake to build the nuget package with the specific version number
4) TeamCity (not cake) creates an Octopus release using the version number.

**Comment by gep13** [comment]
@xclayl Is that version number not available as an environment variable? This is normally what happens with most TeamCity parameters:

https://confluence.jetbrains.com/display/TCD8/Predefined+Build+Parameters

You should be able to use this directly within your build.cake file, rather than worry about passing it in.

**Comment by xclayl** [comment]
The version number is a combination of things, including the Hg change set number. It could be rebuilt in cake but I'd rather pass it in. 

It seems that build.ps1 should do just what it's good at: downloading and updating cake, then let us call cake.exe directly. Build.ps1 parameters then would be something like, -CakeVersion 0.10.x, to indicate I want to stick with bug fixes of a particular version.

**Comment by gep13** [comment]
@xclayl You can already pin to a specific version of Cake by checking in the packages.config file.  have you done this?

We agree that there is currently quite a bit going on in the bootstrapper, and we want to control this going forward.  There is nothing to stop you writing your own bootstrapper, and calling Cake.exe directly, if that is what you want to do.

**Comment by xclayl** [comment]
I've only committed build.ps1 and my build.cake file to Hg, so TeamCity will always grab the latest version of cake.  I'll probably change this to include packages.config (but not packages.config.md5sum? I assume this file shoulnd't be committed if the Cake folder isn't)

Looks like I could do something like this (allowedVersions) to limit the cake version (copied from the nuget site):

`<package id="Newtonsoft.json" version="6.0.4" allowedVersions="[6,7)" />`

I'd still prefer a parameter to not run cake.exe so that I can run it myself since build.ps1 doesn't provide you with every feature cake.exe has.  What do you think?

**Comment by gep13** [comment]
>@xclayl said...
I'd still prefer a parameter to not run cake.exe so that I can run it myself since build.ps1 doesn't provide you with every feature cake.exe has. What do you think?

Sorry, you lost me with this part, can you elaborate?

**Comment by xclayl** [comment]
Yes, so I want to pass a version number from TeamCity to build.cake.  I've worked around it by using environment vars.  TeamCity calls this batch file:

```
PUSHD %~dp0
SET build_version=%1
powershell .\build.ps1 
```
And the build.cake code pulls out the version from the environment vars:
`var version = EnvironmentVariable("build_version") ?? "0.9.0-local";`

At first I came at the challenge by passing command line parameters, but stopped when the documentation said to modify the build.ps1 script.
https://github.com/cake-build/resources/issues/13

As a new user, build.ps1 *is* cake, and cake.exe just some internal executable that you don't touch directly.  I want to agree on this point, because that is the crux of the whole thing.  Though it is really your call.  Do you want us users to call cake.exe directly?

So modifying build.ps1 is really strange, considering build.ps1 *is* cake.  

So that's where I'm at right now.  I'm happy -- I really like cake and I'm happing enough to having a batch file to bridge information from TeamCity to build.cake.  Personally I'd prefer to have a powershell script that just "restores" cake, and call cake.exe directly to get all the features of cake.exe.  I'm not sure it's best for build.ps1 to *become* cake.

**Comment by devlead** [comment]
`build.ps1` and `build.sh` are just boostrappers to fetch the dependencies needed to enable just a clone & execute `build.ps1`/`build.sh` experience to build a repo.
The use is free to modify these according to theirs needs. If the default bootstrappers are doing too much there are examples of where useres have modified them to be simpler and just pass along arguments give to the Cake executable.
I've done this for one of my projects you can see that bootstrapper [here](https://github.com/devlead/BitbucketPipelinesShield)

If you're happy now can we close the issue or are you still having issues?

**Comment by xclayl** [comment]
Yes let's close this -- the original issue is sorted (environment vars)

**Comment by gep13** [comment]
@xclayl I have been meaning to reply to you about this, but I sort of forgot....

I am a little confused by the need for the intermediate batch file.  Why is this required?  As I think I mentioned, I am fairly sure that the version number that TeamCity has is made available as an environment variable, so you can read that directly in the build.cake file.  However, you seem to be passing that as an argument to the batch file, and then setting the variable.  What is this required?

**Comment by xclayl** [comment]
We're not using TeamCity's build number.  We have a script to generate a build number -- it's a combination of the branch name, Hg node and TeamCity build number.

The batch file already exists -- While making changes to the build, I'm also introducing cake.  Ideally the whole TeamCity build will call cake to build it all (including creating the build number which we like), but for now I'm just doing this one bit.

What would be your thoughts if I wrote a .Net version of build.ps1?  Users already have .Net installed, so it seems like it would be a good fit.  The issue is that build.ps1 may require me to reduce the security settings on the TeamCity build server, which I won't like doing.  I imagine others feel the same way.

**Comment by gep13** [comment]
@xclayl you mean a small bootstrapper.exe, that does the same work that is currently in the build.ps1?  Off the top of my head, I don't see an issue with this.  This would be similar to the way that Paket bootstraps itself.

@patriksvensson @devlead ?

**Comment by xclayl** [comment]
@gep13 yes, and even copy paket.bootstrapper.exe's behaviour where it just downloads.  It doesn't call paket.exe.

**Comment by gep13** [comment]
@xclayl again, sounds like an option to me.  @patriksvensson @devlead thoughts?
