### ISSUE TITLE
nuget doesn't download dependencies in the Addins folder

### ISSUE THREAD

**Issue by xclayl** [cake-build/resources#37]
Start with tools\Addins\packages.config:
<?xml version="1.0" encoding="utf-8"?>
```
<packages>
    <package id="Moq" version="4.7.99" />
</packages>

```

run build.ps1.

The Castle.Core package isn't downloaded.

(We're actually using an internal package with a dependency.  Moq is just an example package with a dependency)

**Comment by xclayl** [comment]
Looks like packages.config can't work any other way

**Comment by gep13** [comment]
@xclayl sorry, not sure what you mean by your last statement. Can you clarify?

**Comment by xclayl** [comment]
nuget.exe only restores packages that are explicitly defined in packages.config.  So when using Visual Studio to add Moq, it also adds the package Castle.Core to packages.config for you.

**Comment by gep13** [comment]
@xclayl gotcha.  There is some on-going work in the 0.22.0 release of Cake which should address this issue.  Please follow this PR for more information:

https://github.com/cake-build/cake/issues/1743

**Comment by xclayl** [comment]
Thanks, looking forward to it!
