### ISSUE TITLE
TLS Issue: build.ps1 - Could not download packages.config

### ISSUE THREAD

**Issue by JeremyCade** [cake-build/resources#39]
I have recently seen builds fail on Windows Server 2012 R2 build 9600 with the following: 

```
D:\Jenkins\workspace\project-MFC7ZSI6BD4TDSTZ3QZN42CB6N4YSMKVGVEKCGPUBF3L2K2AFZCA>powershell .\build.ps1 
Preparing to run build script...
Could not download packages.config.
At D:\Jenkins\workspace\project-MFC7ZSI6BD4TDSTZ3QZN42CB6N4
YSMKVGVEKCGPUBF3L2K2AFZCA\build.ps1:126 char:9
+         Throw "Could not download packages.config."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not download packages.c 
   onfig.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not download packages.config.
```

This is due to the an issue with TLS during redirect from https://cakebuild.net/download/bootstrapper/packages to https://raw.githubusercontent.com/cake-build/resources/master/packages.config

Unwrapping the WebClient call results in the following exception: 

```
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
```

**Comment by richev** [comment]
We've seen this today, as of about an hour ago.

Fixed by making this addition to our script to force TLS 1.2

```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
```

**Comment by richev** [comment]
Same issue seen here, fixed as you suggested

```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
```

**Comment by pants4robots** [comment]
The above work around solved this for us as well, thanks.

**Comment by Philo** [comment]
Just as an addition, make sure you add the line:

`[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12`

after the `CmdLetBinding` section

**Comment by devlead** [comment]
CloudFlare has now sorted their issues and SSL handshake should now work as expected.

**Comment by gep13** [comment]
@JeremyCade @richev @pants4robots @Philo if one of you could confirm that it is working again, without the workaround in place, we can get this issue closed out.

**Comment by richev** [comment]
@gep13 happy to confirm that yes, the workaround is no longer needed.

**Comment by patriksvensson** [comment]
Closing issue.

**Comment by gep13** [comment]
@richev thank you for confirming! 👍
