### ISSUE TITLE
Building from VS Code extension fails when inside directory with spaces in name

### ISSUE THREAD

**Issue by Roadrunner67** [cake-build/resources#78]
Create a directory like "C:\Directory with spaces".
Download build.ps1 and sample build.cake.
From within VS Code (with Cake extension) click the "run task" over Task("Default").

This executes:
Powershell -ExecutionPolicy ByPass -File build.ps1 -script "c:\Directory with spaces\build.cake" -target "Default" -verbosity normal

In build.ps1 the quotes surrounding script parameter are lost, leading to:
"More than one build script specified."

**Comment by Roadrunner67** [comment]
The PR #79 should handle this

**Comment by devlead** [comment]
Fixed by #79
