### ISSUE TITLE
build.ps1 uses MD_5 which is forbidden on FIPS compliant computers

### ISSUE THREAD

**Issue by DanFTRX** [cake-build/resources#85]
FIPS enabled computers will fail to create an MD5Hasher in all cases.  Are there alternative FIPS compliant hashes that can be used to verify the nuget downloads?

https://github.com/cake-build/resources/blob/develop/build.ps1#L82

**Comment by devlead** [comment]
I would recommend bootstrapping using .NET Core tool manifest, it's FIPS compliant, you can read more about it at:
https://cakebuild.net/docs/getting-started/bootstrapping-scripts#bootstrapping-for.net-core-tool

**Comment by DanFTRX** [comment]
Thanks.
