### ISSUE TITLE
Add build.sh version for Windows

### ISSUE THREAD

**Issue by tiesmaster** [cake-build/resources#98]
Cake is an excellent tool, and the "Getting Started" guide and this repo really helps to get started. I just [installed](https://github.com/tiesmaster/DCC/commit/083f933ef52f85e02663317a51fe19800dccd1b4) it in my toy project, and was really easy 👍 

However, the `build.sh` script seems only to be working on linux/osx, and not on Windows, since the `build.ps1` is for that. However, with bash becoming more popular on Windows, and having that easily available with Git for Windows, people are starting to use that as a default shell more often. It would be nice if this repo would provide a canonical version for Windows of `build.sh`, or adjust the current one so it also works on Windows.

Could this be added, or do you accept a PR for that?

**Comment by augustoproiete** [comment]
[The .NET Tool runner](https://cakebuild.net/docs/running-builds/runners/dotnet-tool) is now the recommended way to run Cake scripts on all platforms, the bootstrapper became a lot simpler ([a handful of lines of code](https://github.com/cake-build/resources/tree/master/dotnet-tool)), doesn't require Mono (runs on .NET Core) and the `build.sh` now works from the Git Bash on Windows/MSYSGIT.

![Screenshot MSYSGIT running Cake](https://user-images.githubusercontent.com/177608/106838885-7d09d280-6673-11eb-8132-4b94bd7cd560.png)

Closing this as resolved. Feel free to reopen if needed.
